version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: theruzilproxy
    ports:
      - 80:80
      - 443:443
  api:
    image: envoy89/myworstblog:0.0.2
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: blog-api
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: blog-db