version: '3'

services:
  webserver:
    image: nginx:mainline-alpine 
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf/nginx.local.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/mime.types:/var/conf/mime.types
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./site/html
      o: bind

networks:
  app-network:
    driver: bridge