version: '3'

services:
  blog-db:
    image: mongo
    container_name: blog-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - app-network
  blog:
    image: envoy89/myworstblog:0.0.2
    container_name: blog
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - blog-db
    networks:
      - app-network
  webserver:
    image: nginx:mainline-alpine 
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf/nginx.local.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/mime.types:/var/conf/mime.types
    depends_on:
      - blog
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./site/html
      o: bind

networks:
  app-network:
    driver: bridge