name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Publish to pkalkman/mve-workflowengine on Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: envoy89/theruzilproxy
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./Dockerfile
          tags: ${{ steps.bump_version.outputs.next-version }}